server:
  port: 8761

spring:
  application:
    name: eureka-server

eureka:
  client:
    register-with-eureka: false   # Eureka server does NOT register itself
    fetch-registry: false         # Does NOT fetch registry from others
  server:
    enable-self-preservation: false

