spring:
  application:
    name: order-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/orderdb

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

logging:
  level:
    feign: DEBUG
